---
name: docker
on:
  push:
    branches:
      - main
    # paths:
    #   - Dockerfile
    #   - conda-lock.yml
    #   - ppc64le.conda-lock.yml
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space.
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: "true"
          remove-codeql: "true"
          remove-haskell: "true"
          remove-android: "true"
          overprovision-lvm: "true"
          remove-docker-images: "true"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,ppc64le
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          # registry: ${{secrets.GITLAB_REGISTRY}}
          username: ${{secrets.GITLAB_USERNAME }}
          password: ${{secrets.GITLAB_TOKEN }}
      - name: Get torch version amd
        run: "echo TORCH_VERSION_AMD=$(cat conda-lock.yml | grep -E -A 4 'name: pytorch$' |
          tail -n1 | grep -Eo [0-9]+.[0-9]+.[0-9]+) >> $GITHUB_ENV"
      - name: Get cuda version
        run: "echo CUDA_VERSION=$(cat conda-lock.yml | grep -E -A 4 'name:
          pytorch-cuda$' | tail -n1 | grep -Eo [0-9]+.[0-9]+) >> $GITHUB_ENV"
      - name: Build and push AMD
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: maxscha/docker_test:pytorch-${{env.TORCH_VERSION}}-cuda${{env.CUDA_VERSION}}_amd
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push PPC
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/ppc64le
          push: true
          tags: maxscha/docker_test:pytorch-${{env.TORCH_VERSION}}-cuda${{env.CUDA_VERSION}}_ppc64le
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push PPC
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms:  linux/amd64,linux/ppc64le
          push: true
          tags: maxscha/docker_test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
