name: docker

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'conda-lock.yml'
      - 'ppc64le.conda-lock.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space. # Required for building large docker images
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-codeql: 'true'
          remove-haskell: 'true'
          remove-android: 'true'
          overprovision-lvm: 'true'
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.DOCKER_REGISTRY}}
          username: ${{secrets.DOCKER_USERNAME }}
          password: ${{secrets.DOCKER_TOKEN }}
      - 
        name: Get torch version
        run: echo TORCH_VERSION=$(cat conda-lock.yml | grep -E -A 4 'name: pytorch$' | tail -n1 | grep -Eo [0-9]+.[0-9]+.[0-9]+) >> $GITHUB_ENV
      - 
        name: Get cuda version
        run: echo CUDA_VERSION=$(cat conda-lock.yml | grep -E -A 4 'name: pytorch-cuda$' | tail -n1 | grep -Eo [0-9]+.[0-9]+) >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          no-cache: true
          push: true
          tags: ${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_REPOSITORY}}:pytorch-${{env.TORCH_VERSION}}-cuda${{env.CUDA_VERSION}}
